### ISSUE TITLE
Error setting announce list

### ISSUE THREAD

**Issue by luckiestone** [xavery/transgui#65] opened 2023-11-16 08:49 UTC
If multiple items are selected and announce tracker in properties is changed, there would be an error `Error setting announce list`
Do know if this is a issue caused by TR4, as mentioned in https://github.com/transmission-remote-gui/transgui/issues/1428#issuecomment-1426676713

**Comment by xavery** [comment] 2023-11-18 15:36
This shouldn't be caused by what I described in that other comment as all the RPC endpoints that transgui uses are still functional, though deprecated.

Can you describe what you're trying to do in more detail (from what I understand, changing the announce address for multiple selected torrents at the same time), and the version of the daemon that you're running?

**Comment by luckiestone** [comment] 2023-11-18 15:45
> This shouldn't be caused by what I described in that other comment as all the RPC endpoints that transgui uses are still functional, though deprecated.
> 
> Can you describe what you're trying to do in more detail (from what I understand, changing the announce address for multiple selected torrents at the same time), and the version of the daemon that you're running?

Yes, that's what I did. I was previously using transgui https://github.com/transmission-remote-gui/transgui/releases/tag/v5.18.0 with same issue. The daemon version is 4.0.3, I'll try to update it to latest.

**Comment by xavery** [comment] 2023-11-18 15:48
If this happened with 5.18.0, then it's either a bug in transgui which incorrectly generates the RPC requests (more likely IMHO) or a bug introduced in the daemon between v4 and older versions (less likely but not impossible). I'll test with different versions so we know what's going on.

**Comment by luckiestone** [comment] 2023-11-18 15:55
thank you, updated to 4.0.4 but no luck. I'm sure that no such bug with 5.18.0 with v3, but not sure if it's introducted in the first release of v4.

**Comment by xavery** [comment] 2023-11-18 16:31
Looks like this is a Transmission bug after all, I tested both transgui 5.18.0 and 5.18.4f with daemons 2.94 and 4.10-dev. Connecting to 2.94 results in the tracker list being updated successfully.

I'll file a issue in the Transmission project once I collect more information.

**Comment by xavery** [comment] 2023-11-19 20:50
Bringing back the `bug` label as transgui's behaviour isn't 100% correct here either, as it assumes that tracker IDs are indices to an array of consecutively stored tracker addresses. This is not true anymore with 4.0 and has never been specified explicitly so transgui (knowingly or not) relies on undocumented behaviour.

I do hope that the Transmission issue ends up bringing back the old ID semantics as they allow to perform `trackerRemove` more efficiently - however, behaviour with current 4.0 versions still must be fixed so a fix in transgui is needed anyway.

transgui should use `torrent-set::trackerList` anyway when RPC version is >= 17.

**Comment by luckiestone** [comment] 2023-12-04 01:10
> @luckiestone The newest builds will use `trackerList` when talking to Transmission 4.0 or newer, and my testing has shown that this error is no longer returned and trackers are set properly for multiple torrents.
> 
> Please try out the development builds ([Linux](https://github.com/xavery/transgui/suites/18710846328/artifacts/1089178736), [Windows](https://github.com/xavery/transgui/suites/18710846330/artifacts/1089179136), [macOS](https://github.com/xavery/transgui/suites/18710846331/artifacts/1089178742)) and let me know if this is fixed for you too.

Thank you! I've done some tests, and it's fixed for tr4. However, when I connect to tr2.94. Setting announce list even for one single torrent shows `Privileged instruction`, and the GUI crashed.

**Comment by lighterowl** [comment] 2023-12-04 19:58
@luckiestone Thanks for testing. This was caused by a very embarrassing mistake on my part. Please try out the newer builds : [macOS](https://github.com/xavery/transgui/suites/18745223424/artifacts/1091659705), [Linux](https://github.com/xavery/transgui/suites/18745223419/artifacts/1091659309), [Windows](https://github.com/xavery/transgui/suites/18745223417/artifacts/1091659610)

**Comment by lighterowl** [comment] 2023-12-09 10:32
Closing as fixed in latest release. Please create a new issue if you still experience problems.

**Closed by lighterowl** 2023-12-09 10:32 UTC
Labels: bug, transmission-bug
