### ISSUE TITLE
UI color issue after switching between light/dark mode on macOS

### ISSUE THREAD

**Issue by kailiu42** [xavery/transgui#57] opened 2023-10-14 01:18 UTC
Some UI element remains dark background after the OS switched from dark to light mode, make the text unreadable and the UI look strange. Would you please take a look?

<img width="848" alt="Snipaste-20231014-091437" src="https://github.com/xavery/transgui/assets/358679/fe2fe50c-88ae-4128-8c8a-a743174fc16e">

<img width="695" alt="Snipaste-20231014-091448" src="https://github.com/xavery/transgui/assets/358679/8f00f0f0-4c88-4b35-9d64-9972dbc6bdbf">

**Comment by xavery** [comment] 2023-10-14 05:03
Thanks, it can't be a coincidence that it's every 2nd row.

**Comment by wayward-turnip** [comment] 2023-10-19 18:18
This was reported here, and your fix @xavery would also fix the issue on the upstream project.
https://github.com/transmission-remote-gui/transgui/issues/1366

**Comment by xavery** [comment] 2023-10-19 22:06
The colour used to draw even-numbered rows is called `AlternateColor` in Lazarus' `TGrid` classes, and transgui sets it for all grids used in the program inside `TMainForm.FormCreate` :
```
gTorrents.AlternateColor:=FAlterColor;
lvPeers.AlternateColor:=FAlterColor;
lvTrackers.AlternateColor:=FAlterColor;
gStats.AlternateColor:=FAlterColor;
```

The problem is that `TMainForm.FormCreate` is only called once so this value remains the same throughout the whole program, without taking into account any potential dark/light theme changes.

There is [a solution](https://forum.lazarus.freepascal.org/index.php/topic,43111.msg461112.html#msg461112) available which gets a "theme changed" notification straight from the OS so it sounds like it's going to be possible to set those colours to new theme-appropriate values.

**Comment by xavery** [comment] 2023-10-21 15:43
Dark/light theme transitions should be now fixed. Hyperlinks now use a lighter shade of blue in dark mode which is much more readable :
![foo](https://github.com/xavery/transgui/assets/127875/a7180d8e-b2ee-4be6-ad75-3617f1e9c390)

The latest build from master incorporates these changes : https://github.com/xavery/transgui/suites/17484835100/artifacts/999179257

**Comment by kailiu42** [comment] 2023-10-22 01:17
The torrent list view is OK with the latest build now. However the downloaded progress bar in the general panel still has problem.

The bar after switched from dark to light:
<img width="1491" alt="Snipaste-20231022-091456" src="https://github.com/xavery/transgui/assets/358679/158fdb4e-8421-4293-bcea-42514a8d80bd">

The bar after restarted transgui, which should be the correct color:
<img width="1494" alt="Snipaste-20231022-091516" src="https://github.com/xavery/transgui/assets/358679/86ca1aa2-9c96-4d75-9a37-acc2e87e36a5">

**Comment by xavery** [comment] 2023-10-22 10:43
Thanks @kailiu42 , great catch.

The progress bar uses a custom drawing procedure which needs the data from the currently selected torrent. This means that the colour change will be a bit delayed to the app's theme change but will happen eventually (depending on your refresh interval) : 

https://github.com/xavery/transgui/assets/127875/594397aa-c099-4805-ba20-d5673538a56a

I'm sure there's a way to call this procedure from the theme change callback but I kept getting weird crashes that I couldn't figure out.

**Comment by kailiu42** [comment] 2023-10-22 14:55
It works now. Thanks a lot @xavery for your great help!

**Closed** 2023-10-22 15:04 UTC
Labels: bug
