### ISSUE TITLE
Moving or Deleting does not work (with newer daemons)

### ISSUE THREAD

**Issue by fredo-47** [xavery/transgui#79] opened 2024-02-10 14:28 UTC
I noticed that on my harddisk, there are still files which I had removed earlier from my transmission-daemon with transgui's "Remove torrent and data". Apparently, only the torrents were removed (resume and torrent file), but the actual data file remained on disk.

Similarly, when I use "Set data location", and choose to move the file to another place, the change is reflected in the resume-file, but the actual data file is not moved.

Both functions have worked before (some time ago?).
Not sure, this may be related to a change in transmission-daemon itself?
I am using latest dev version `9bc8ed8e46`

But, both mentioned functions still work as expected when executing it via commandline `transmission-remote`, e.g. with parameters `-rad` or `--move`.
They also work, when using the web interface (I use Shift).

Testing with some older daemon builds, I find that e.g. `9c4d28dd08` from December 30 is still working normally.
And that e.g. `4cfd9f0c9e` from January 4 comes with the issues described above.

**Comment by lighterowl** [comment] 2024-02-12 20:52
Hi there, thanks for the report.

I can confirm that something's wrong indeed when running today's HEAD, i.e. `f06cb37c0`. The captured RPC exchanges show that `torrent-set-location` is reported as executed successfully by the daemon, but after that transgui goes into some weird state where it starts requesting torrent data every 0.2 seconds for some reason and it makes the whole GUI unusable. The torrent data in question isn't moved to its destination either.

Will investigate further as time allows.

**Comment by lighterowl** [comment] 2024-02-12 21:13
OK, not a Transmission bug. Transgui is to blame here because it sends the `move` argument to `torrent-set-location` as an integer, while it has been specified as a boolean [since 2009 when it was originally introduced](https://github.com/transmission/transmission/blob/29b1d3e2ccb1c6185ff3dd3902c516ab8038e748/doc/rpc-spec.txt#L358).

The recent [commit `22cde5d` in Transmission](https://github.com/transmission/transmission/commit/22cde5d4b9ac43ac73f1309cb1021f0dd187e9f0) actually starts enforcing this : as opposed to the previously used `tr_variantDictFindStrView` which performed conversions from int to bool, the new `value_if<bool>` just returns an empty optional which is then converted to the default value of false via `value_or(false)`.

The same applies to `delete-local-data` in `torrent-remove`.

**Comment by lighterowl** [comment] 2024-02-12 22:57
Further investigation revealed that transgui's original author must've really disliked booleans for some reason as almost all `boolean` arguments to RPC functions were read and/or set as integers. I think I got them all.

Please test out the latest build from `develop` and let me know if stuff is still broken.

I don't run development versions of the daemon, so thanks again for testing this.

**Comment by fredo-47** [comment] 2024-02-13 19:31
Thank you. Moving and deleting now works as expected.

Any chance that this can also be put in the original transgui at https://github.com/transmission-remote-gui/transgui?
Can you (sorry, I don't know what the correct term is) upload/suggest/merge your patch there too?

**Comment by lighterowl** [comment] 2024-02-13 21:51
Thanks, closing in this case.

I'll submit the patch to the main fork if it isn't too much work.

**Closed as completed by lighterowl** 2024-02-13 21:51 UTC
Labels: bug
