### ISSUE TITLE
Showing a torrent completed notification brings the main window to the foreground

### ISSUE THREAD

**Issue by metaclam** [xavery/transgui#83] opened 2024-05-15 17:33 UTC
Maybe I'm missing a setting, but can we turn off the notification for completed torrents?  Can we at least not have the app foreground itself when a torrent is completed?

On MacOS Sonoma.

**Comment by lighterowl** [comment] 2024-07-07 00:20
The application doesn't foreground itself when a torrent is completed on Windows or Linux, so this is macOS specific (and unwanted, I presume) behaviour.

You can turn off notifications by unchecking `Tools > Application options > Show notifications in tray icon`. This is enabled by default.

**Comment by lighterowl** [comment] 2024-07-07 10:08
Can't reproduce on Big Sur, will try Sonoma once I get around to installing it.

**Comment by lighterowl** [comment] 2024-07-07 22:20
Sorry, this appears to be standard Lazarus behaviour on macOS. I reproduced this on Big Sur too.

I created a very simple application that shows a window and starts a 10-second timer. When the timer interval elapses, a notification is shown by using `TTrayIcon.ShowBalloonHint`, the same function that transgui uses. After starting the application and letting it run in the background, it foregrounds itself after 10 seconds when the pop-up is shown.

Here's the Lazarus bug report : https://gitlab.com/freepascal.org/lazarus/lazarus/-/issues/41016

A proper fix for this would be to [use the macOS APIs for delivering notifications](https://developer.apple.com/documentation/usernotifications/scheduling-a-notification-locally-from-your-app) but given my total lack of experience with macOS and ObjC/Pascal bindings, I'm not signing up for that. The [Lazarus wiki](https://wiki.lazarus.freepascal.org/macOS_User_Notifications) has some example code, but it uses the API that was deprecated in macOS 11.

**Comment by lighterowl** [comment] 2024-07-09 20:20
Great news, the bug report was picked up by a Lazarus developer who implemented support for native notifications on macOS. This means that notifications are now going to look like this :
![Screenshot_2024-07-09_22-14-04](https://github.com/lighterowl/transgui/assets/127875/4d3eb684-7902-4dfa-99d1-1c6de1485ee9)

(don't pay attention to the icon as this was running in a makeshift AppBundle)

In line with standard macOS behaviour, you will need to allow displaying notifications from transgui when it first tries to display one :
![Screenshot_2024-07-09_22-12-13](https://github.com/lighterowl/transgui/assets/127875/64be6efe-4805-46db-8b6d-8368db5b066f)

It should also be possible to block notifications in system settings instead of just in the application itself. Of course, the application's main window is no longer brought to the foreground.

I will close this ticket once I integrate the new Lazarus code into my own fork and first transgui builds with this feature are available.

**Closed as completed** 2024-07-11 18:19 UTC
Labels: bug, os:mac

**Comment by lighterowl** [comment] 2024-07-11 18:20
Tested on Intel Big Sur, Intel Sonoma, and M1 Monterey.
